Repository SurajSanap/College.ai-main, pull requests merged in 2024-06, with the labels that each got.

#34 Added an Issue Template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: documentation, gssoc

#55 Update README.md
  README.md
Labels: gssoc, level1, feature

#56 Update About.py
  menu/About.py
Labels: enhancement, good first issue, gssoc, level2

#58 Update README.md
  README.md
Labels: documentation, gssoc, level2

#59 Add files via upload
  webScrap.py
Labels: bug, gssoc, level2

#60 Dipti sanap patch 1
  webScrap.py
Labels: documentation, gssoc, level2

#62 Dipti sanap patch 3
  .devcontainer/devcontainer.json
Labels: documentation, gssoc, level2

#61 Dipti sanap patch 2
  ResumeSkillCounter.txt
Labels: documentation, gssoc, level2

#66 Update README with Example Usage Instructions for Ask_To_PDF, Resume_Analyser, and ATS
  GitHub/College.ai-main/src/ats_feedback.png
  README.md
  src/ask_to_pdf_query.png
  src/ask_to_pdf_response.png
  src/ats_feedback.png
  src/ats_upload.png
  src/resume_analyser_analysis.png
  src/resume_analyser_upload.png
  src/sk_to_pdf_upload.png
Labels: documentation, gssoc, level2

#70 Update Home.py
  Home.py
Labels: bug, gssoc, level1

#71 Delete GitHub/College.ai-main/src directory
  GitHub/College.ai-main/src/ats_feedback.png
Labels: bug, gssoc, level2

#72 Update Home.py
  Home.py
Labels: gssoc, level1, feature

#73 Update Home.py
  Home.py
Labels: bug, level2

#75 Update and rename config.toml.txt to config.toml
  .streamlit/config.toml
  .streamlit/config.toml.txt
Labels: gssoc, level2, feature

#77 Update Home.py
  Home.py
Labels: bug, gssoc, level1, level2

#78 Update Resume_Analyser.py
  menu/Resume_Analyser.py
Labels: bug, good first issue, gssoc, level2

#86 Update README.md
  README.md
Labels: documentation, gssoc, level2

#88 Shifting the theme button #87
  Home.py
Labels: enhancement, gssoc, level3

#98 shifting theme button
  Home.py
Labels: enhancement, gssoc, level3

#91 Fix sidebar with a proper alignment and good color
  Home.py
  src/style.css
Labels: gssoc, level2, feature

#108 Add the contest calendar module
  Home.py
  README.md
  menu/Contest_Calendar.py
  src/contest.json
Labels: gssoc, level3, feature

#109 Revert "Add the contest calendar module"
  Home.py
  README.md
  menu/Contest_Calendar.py
  src/contest.json
Labels: bug

#111 Revert "Contest Calendar bug "
  README.md
  requirements.txt
Labels: bug
