Repository SurajSanap/College.ai-main, pull requests merged in 2024-05, with the labels that each got.

#17 feat: beautified the navbar and refactored the code ; resolves #7
  1_🏠Home.py
  README.md
  menu/AI_Lens.py
  menu/ATS.py
  menu/About.py
  menu/Ask_To_PDF.py
  menu/Prompt_Examples.py
  menu/Resume_Analyser.py
  menu/User.py
  menu/__init__.py
  pages/5_💼ATS.py
  pages/9_✏️Prompt_Examples.py
  requirements.txt
  src/style.css
Labels: enhancement, Gssoc, level1

#20 Update README.md
  README.md
Labels: gssoc

#23 Added Learn.md
  Learn.md
Labels: documentation, gssoc, level3

#29 Required changes in format
  Home.py
  menu/AI_Lens.py
  menu/About.py
  menu/Ask_To_PDF.py
  menu/Prompt_Examples.py
  menu/Resume_Analyser.py
  menu/User.py
Labels: gssoc, level1

#32 Update User.py
  menu/User.py
Labels: bug, gssoc, level1

#31 Adding enhanced readme
  README.md
Labels: documentation, level1
